// API
export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'

export const LOAD_USER = '@@INCONNECT/LOAD_USER'
export const LOAD_SECURITYSCORE = '@@INCONNECT/LOAD_SECURITYSCORE'

export const USERDEVICE_LIST = '@@INCONNECT/USERDEVICE_LIST'
export const LOAD_USERDEVICES = '@@INCONNECT/LOAD_USERDEVICES'

export const USERNOTIFICATION_LIST = '@@INCONNECT/USERNOTIFICATION_LIST'
export const LOAD_USERNOTIFICATIONS = '@@INCONNECT/LOAD_USERNOTIFICATIONS'

export const INSURANCE_LIST = '@@INCONNECT/INSURANCE_LIST'
export const LOAD_INSURANCE = '@@INCONNECT/LOAD_INSURANCE'
export const CHANGE_ENTITY_INSURANCE_NODE = '@@INCONNECT/CHANGE_VALUE_INSURANCE_NODE'

// FILTERS
export const CHANGE_FILTERS = '@@INCONNECT/CHANGE_FILTERS'